# Generated by Django 6.0.4 on 2026-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
